# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b2352c2f85612936dee8738deee6dcee8361a321bbccebc294c25cd9c9388a1b24055d7743fcb55ca74fa5a3a71ca854c51560c689b541ef3210a4df6183230

test:
  secret_key_base: eba8d530a92e443e55c2137a44aa9b5baa578bdf716805cca3bd1e8d7cb73d6c3dd64aebc83dad2ca2e88fc6b4afd34b75b435cb142f76bb710f2bbfcc188244

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
